### PR TITLE
training dropdown

### PR DESCRIPTION
**Pull request by mwernimont**
@lindsaycarr Training drop down code for actual USGS-R website. The hugo site code to come

### CODE REVIEW

**Comment by lindsaycarr** [comment]
just tested it out locally :heart: 

is Hugo part coming in a different PR or can I merge this?

**Comment by lindsaycarr** [comment]
Should clicking "Training" bring you somewhere different than "Training Schedule"? I think I might make a new page in the future to describe the different types of training we offer, but for now we can let them go to the same place

**Comment by mwernimont** [comment]
@lindsaycarr I don't think having the nav link be a different link than one on the dropdown, if theres a drop down the likily hood of a user clicking the nav link goes down considerably

**Comment by mwernimont** [comment]
but merge away!

**Pull request merged**
