### PR TITLE
adding geoknife

### PR DESCRIPTION
**Pull request by jread-usgs**
#58 @ldecicco-USGS can you review?

@lawinslow not sure how the ordering is handled. For some reason, this made geoknife first for me locally. Probably don't want it first.

### CODE REVIEW

**Comment by ldecicco-USGS** [comment]
I also see geoknife coming in first...not sure why.

**Comment by jread-usgs** [comment]
oh. I know why. they are still sorted by "Last touched" in the json.
I've got a fix

**Comment by jread-usgs** [comment]
by the way, it is the "pushed_at" time, not the "updated_at" time that is used for sorting. Update coming shortly

**Comment by jread-usgs** [comment]
@ldecicco-USGS try again?

**Comment by ldecicco-USGS** [comment]
beauty

**Pull request merged**
